### ISSUE TITLE
Redis create cluster issue

### ISSUE THREAD

**Issue by ellik95** [redis/node-redis#1782]
Hello,
I have a Redis MemoryDB cluster with 2 nodes in AWS and I'm trying to connect to it through `createCluster`, but the connection isn't established.
Here is how I try to connect:
```
import { createCluster } from 'redis';
(async () => {
    const REDIS_USERNAME = 'test-username';
    const REDIS_PASSWORD = 'test-pass';
    const cluster = createCluster({
        rootNodes: [
            {
                url: `rediss://redis-region-0001-001.amazonaws.com:6379`,
                username: REDIS_USERNAME,
                password: REDIS_PASSWORD,
            },
            {
                url: `rediss://redis-region-0001-002.amazonaws.com:6379`,
                username: REDIS_USERNAME,
                password: REDIS_PASSWORD,
            },
        ]
    });
    cluster.on('error', (err) => console.log('Redis Cluster Error', err));
    console.log('before connection');
    await cluster.connect();
    console.log('connected to cluster...');
    await cluster.set('key', 'value');
    const value = await cluster.get('key');
    console.log(value);
    await cluster.disconnect();
})();
```
The log `connected to cluster...` is never showed up.
If I add in the configuration of `createCluster` to the `defaults` option the master node endpoint like this:

```
defaults: {
            url: `rediss://redis-region-0001-001.amazonaws.com:6379`,
            username: REDIS_USERNAME,
            password: REDIS_PASSWORD,
        }
```
The connection is established and everything works fine!
Why do I need the defaults option? Shouldn't it work only with rootNodes?
Thank you!

**Environment:**
 - **Node.js Version**: 16-alpine3.12
 - **Redis Server Version**: 6
 - **Node Redis Version**: 4.0.0

**Comment by leibale** [comment]
As described in the [clustering guide](https://github.com/redis/node-redis/blob/master/docs/clustering.md#createcluster-configuration):
- `rootNodes` - "An array of root nodes that are part of the cluster, which will be used to get the cluster topology. Each element in the array is a client configuration object. There is no need to specify every node in the cluster, 3 should be enough to reliably connect and obtain the cluster configuration from the server"
- `defaults` - "The default configuration values for every client in the cluster. Use this for example when specifying an ACL user to connect with"

node-specific properties should be listed in `rootNodes`, the rest in `defaults`

 ```javascript
createCluster({
  rootNodes: [{
    url: `rediss://redis-region-0001-001.amazonaws.com:6379`
  }, {
    url: `rediss://redis-region-0001-002.amazonaws.com:6379`
  }],
  defaults: {
    username: REDIS_USERNAME,
    password: REDIS_PASSWORD
  }
});
```

**Comment by ellik95** [comment]
I had tried this also and the same thing happened!

**Comment by ellik95** [comment]
Could you please reopen the issue?

**Comment by leibale** [comment]
@ellik95 It didn't work even when the username & password are in the `defaults` object? can you please share your code?

**Comment by ellik95** [comment]
Yes, with this code:
```
import { createCluster } from 'redis';
(async () => {
    const REDIS_USERNAME = 'test-username';
    const REDIS_PASSWORD = 'test-pass';
    const cluster = createCluster({
        rootNodes: [
            {
                url: `rediss://redis-region-0001-001.amazonaws.com:6379`
            },
            {
                url: `rediss://redis-region-0001-002.amazonaws.com:6379`
            },
        ],
       defaults: {
            username: REDIS_USERNAME,
            password: REDIS_PASSWORD,
        }
    });
    cluster.on('error', (err) => console.log('Redis Cluster Error', err));
    console.log('before connection');
    await cluster.connect();
    console.log('connected to cluster...');
    await cluster.set('key', 'value');
    const value = await cluster.get('key');
    console.log(value);
    await cluster.disconnect();
})();
```
it is not connected. Only if I add the url of the master node to the defaults options works. Like this:
```
defaults: {
            url: `rediss://redis-region-0001-001.amazonaws.com:6379`,
            username: REDIS_USERNAME,
            password: REDIS_PASSWORD,
        }
```
And I was wondering why is this needed.

**Comment by leibale** [comment]
```javascript
createCluster({
  rootNodes: [{
    url: `rediss://redis-region-0001-001.amazonaws.com:6379`
  }, {
    url: `rediss://redis-region-0001-002.amazonaws.com:6379`
  }],
  defaults: {
    username: REDIS_USERNAME,
    password: REDIS_PASSWORD,
    tls: true
  }
});
```

**Comment by ellik95** [comment]
It's not working either and 'tls' option does not exist in type 'Partial<RedisClusterClientOptions>'.

**Comment by leibale** [comment]
@ellik95
```createCluster({
  rootNodes: [{
    url: `rediss://redis-region-0001-001.amazonaws.com:6379`
  }, {
    url: `rediss://redis-region-0001-002.amazonaws.com:6379`
  }],
  defaults: {
    socket: {
      tls: true
    },
    username: REDIS_USERNAME,
    password: REDIS_PASSWORD
  }
});
```

**Comment by ellik95** [comment]
Unfortunately it is not working either. Only with the below code is:
```
createCluster({
  rootNodes: [{
    url: `rediss://redis-region-0001-001.amazonaws.com:6379`
  }, {
    url: `rediss://redis-region-0001-002.amazonaws.com:6379`
  }],
  defaults: {
    url: `rediss://redis-region-0001-001.amazonaws.com:6379`
    username: REDIS_USERNAME,
    password: REDIS_PASSWORD
  }
});
```

**Comment by ellik95** [comment]
Also when I connect I sometimes get the error `ReplyError: MOVED 12539 rediss://redis-region-0001-002.amazonaws.com:6379` and I cannot get the value from the key.

**Comment by lohanbodevan** [comment]
Same issue as @ellik95. 
I'm trying to connect with a Redis cluster running on Kubernetes and the connection is always `ReplyError: MOVED xxxx`
In my case I have Load Balancer to connect with, so I'm using `createClient` rather than `createCluster`.

Connection through `redis-client` command line works fine, though.
Is there any specific configuration we have to do with `createClient` when using Load Balanced redis cluster?

**Comment by acb** [comment]
I'm having the same issue with elasticache and the `createCluster` function, it just hangs indefinitely when you call `cluster.connect()` unless you provide a `url` entry in the `defaults` object.

However, when you do that it seems like it _only_ connects to that node.  If you try to access a key that gets sorted onto one of the other nodes you get the MOVED error.

@leibale I see that you mentioned this issue on https://github.com/redis/node-redis/pull/1827 but I'm not sure how that would apply to solve this issue.  My server has access to the elasticache nodes just fine, it can connect to any of them individually with `createClient` but `createCluster` isn't able to `connect` unless you provide that default url.

**Comment by leibale** [comment]
@acb [this line](https://github.com/redis/node-redis/pull/1827/files#diff-37689a0d5cacc40d30e634234217fd65655a4ac0e9bb345c8e18201056ddcc97R133) should fix it

**Comment by acb** [comment]
@leibale oh, awesome! Do you have any idea when that might be pushed out in a release?

**Comment by leibale** [comment]
@acb Sunday/Monday :)

**Comment by acb** [comment]
@leibale I just tried release 4.0.4 and unfortunately I'm still having the same problem.  With the code 

```
const client = createCluster({
    rootNodes: [
        {
            url: "rediss://reids-1-url:6379",
        },
        {
            url: "rediss://reids-2-url:6379",
        },
        {
            url: "rediss://reids-3-url:6379",
        },
    ],
    defaults: {
        password: "EFrp9Dpxgt!pAHw4eGuV"
    }
});
client.on("error", (err: any) => {
    console.log("REDIS ERROR");
    console.log(err);
});

console.log('connecting to redis');
client.connect().then(() => {
    console.log('connected to redis');
});
```
I see 'connecting to redis' in my logs but it seems to hang and never actually connects.  If I update my defaults array to be 

```
    defaults: {
        url: `rediss://redis-1-url:6379`,
        password: "EFrp9Dpxgt!pAHw4eGuV"
    }
```
Then in my logs I get 'connecting to redis' followed immediately by 'connected to redis', but the connection is only to the one redis server that's in the default.  If I try to sample random keys 2/3rds of them return with something like `MOVED 11388 redis-2-url`.

**Comment by leibale** [comment]
@acb try this

```javascript
const client = createCluster({
    rootNodes: [
        {
            url: "rediss://redis-1-url:6379",
        },
        {
            url: "rediss://redis-2-url:6379",
        },
        {
            url: "rediss://redis-3-url:6379",
        },
    ],
    defaults: {
        password: "password123",
        socket: { tls: true }
    }
});
```

**Comment by acb** [comment]
@leibale you're a wizard!  That did it, I'm getting successful cluster connections now.  I thought that having `rediss` as the protocol would handle the tls-ing but I guess cluster mode handles things a little differently.

Thanks so much for the help!

**Comment by killdash9** [comment]
For me, I found both the :6379 and the extra s in rediss:// to be unnecessary.  This worked:
```
const client = createCluster({
    rootNodes: [
        {
            url: "redis://redis-1-url",
        },
        {
            url: "redis://redis-2-url",
        },
        {
            url: "redis://redis-3-url",
        },
    ],
    defaults: {
        password: "password123",
        socket: { tls: true }
    }
});

```

**Comment by nixRajan** [comment]
I am still getting the Error `MOVED 12218 ip:6379`.
Following is the code
`const client = createClient({url: `redis://xyz.abc.clustercfg.use2.cache.amazonaws.com:6379});
await client.connect();
console.log("client connected");
console.log(await client.ping());
`
I do get the output : "client connected" and "PONG".
But when i do `await client.get()` or `await client.set()` i get the MOVED error.

**Comment by nixRajan** [comment]
This is to way to connect for above issue.

```
    const redis = require('redis');

    const client = redis.createCluster({
      rootNodes: [
        {
          url: `redis://${ConfigurationEndpoint}:${port}`,
        },
      ],
      useReplicas: true,
     });
```

**Comment by winchell** [comment]
This issue was unexpected and seems like a severe high level bug. Spent hours trying to `createCluster` with a k8s redis-cluster using the bitnami Helm charts in GKE.  I see that `nodeAddressMap` is supposed to address the topology definition problem, but what happens when you nuke the pods and k8s assigns new local IPs? It's not a good solution if the client config has to be changed at that point.  

I switched to `ioredis` and connectivity worked out of the box using a single endpoint from the cluster. Confirmed that keys are evenly distributed across all redis nodes. The bitnami helm chart properly sets `cluster-announce-ip` in all the redis.conf files, so that info must be surfaced somewhere and `ioredis` knows how to get it.

**Comment by winchell** [comment]
I'd posted a different comment but just want to leave it like this. Using bitnami Helm redis-cluster charts in GKE.

With `node-redis`, this does not work. The client hangs. Is something wrong with this format?

```
const redis = createCluster({
    rootNodes: [
        {
            url: "redis://<pod-name>.<headless-svc-name>.default.svc.cluster.local:6379"
        },
    ]
});
```

With `ioredis` this _does_ work and keys are distributed as expected: 

```
const redis = new Redis.Cluster([
    {
        port: 6379,
        host: "<pod-name>.<headless-svc-name>.default.svc.cluster.local",
    }
]);
```

**Comment by Eshya** [comment]
@leibale I have new problem with connecting from docker. When I run it in the node environment it runs successfully. But the connection fails when I run it in the docker environment . Got disconnected and reconnecting again

**Comment by nibblesnbits** [comment]
Has this ever been addressed?  I can't go to production with MemoryDB if this isn't fixed, and the approaches noted here result in an infinite loop of trying connection to localhost.

**Comment by leibale** [comment]
@nibblesnbits none of these worked for you?
https://github.com/redis/node-redis/issues/1782#issuecomment-1048241231
https://github.com/redis/node-redis/issues/1782#issuecomment-1003704869

wanna share some code?

**Comment by nibblesnbits** [comment]
Well it looks like lack of sleep and attention to detail killed me.  I missed that the call was `createCluster`, not `createClient`. 🤦‍♂️

**Comment by cb-rnag** [comment]
> For me, I found both the :6379 and the extra s in rediss:// to be unnecessary. This worked [...]

@killdash9  correct. Not sure what the implications are, but `redis://` instead of `rediss://` appears to work. Port seems unnecessary too. 

With those changes my code now becomes:

```ts
import { createCluster } from "redis";

const socket = {
	tls: true,
	rejectUnauthorized: false, // Disable certificate validation
};

// Assuming you're using a Redis client that supports cluster mode and TLS
const redisClient = createCluster({
	rootNodes: [
		{
			url: "redis://<shard #1, node #1 endpoint>",
		},
		{
			url: "redis://<shard #2, node #1 endpoint>",
		},
		{
			url: "redis://<shard #3, node #1 endpoint>",
		},
	],
	defaults: {
		password: "TODO",
		socket,
	},
});
```

**Comment by huan086** [comment]
I had issues with hanging at `await redisClient.connect()`. What worked for me is to remove `useReplicas`. Not sure if it was due to my Redis replicas being on port 6380 and my masters on 6379

```ts
const client = createCluster({
    RESP: 3,
    //// useReplicas: true,
    rootNodes: [
        {
            url: "rediss://redis-1-url:6379",
        },
        {
            url: "rediss://redis-2-url:6379",
        },
        {
            url: "rediss://redis-3-url:6379",
        },
        {
            url: "rediss://redis-1-url:6380",
        },
        {
            url: "rediss://redis-2-url:6380",
        },
        {
            url: "rediss://redis-3-url:6380",
        },
    ],
    defaults: {
        username,
        password,
        socket: { tls: true, ca, cert, key }
    }
}).on("error", (err) => console.log("Redis cluster error", err));
```
